### ISSUE TITLE
Add `change target` strategies

### ISSUE THREAD

**Issue by peonso** [peonso/tibialegacyserver#37]
Add monsters `change target` strategies as they actually were. @HeavenIsLost @CristoferMartins

**Comment by HeavenIsLost** [comment]
@peonso Fico pensando se não seria melhor usar uma engine atual(1.2). Alem disso, fazer um programa pra converter o mapa original do 7.7 e até os respawns se quiser.

**Comment by peonso** [comment]
It will be handled in issue #13.

**Comment by peonso** [comment]
It will be handled in issue #13.
