### ISSUE TITLE
Map corpses are decaying

### ISSUE THREAD

**Issue by peonso** [peonso/tibialegacyserver#51]
as title says

**Comment by tarantonio** [comment]
Use the replace function on remere's to change all at a time ;-P

**Comment by peonso** [comment]
To which one? xD That is my problem. I was thinking about actually having map starting items to not decay, any kind of item.

**Comment by tarantonio** [comment]
Check my map, I think it was solved ages ago.

**Comment by peonso** [comment]
Just checked, same corpses. Can you send me your items.xml?

**Comment by tarantonio** [comment]
I'm using now your items.xml, I send you my old one.

**Comment by peonso** [comment]
You sent me map, movements and actions.

Edit: ahhh got it!

**Comment by tarantonio** [comment]
check your gmail now

**Comment by peonso** [comment]
No difference regarding corpses.

**Comment by tarantonio** [comment]
It's the same as fields, there are corpse ids that not decay. I don't remember the correct ids now, but it's not difficult to check, place all corpses in a map and let them decay. Pick the not decaying ones ;-P

**Comment by tarantonio** [comment]
ID: 2317 ?

**Comment by peonso** [comment]
### DECAYING

3060 - human skel
3112 - bear
3115 - ghoul
3118 - cyclop
3130 - male
3131 - male
3132 - male
3133 - human skel
3134 - human skel

### NOT

3065 - female
3066 - female
3103 - skel
3106 - dragon
3128 - male
3129 - male

**Comment by tarantonio** [comment]
Remere has a replace function, to replace all items one for another in the map.

**Comment by peonso** [comment]
Containers items don't decay, items that are not container do decay. Simple replacing won't solve it as there is no human skeleton that do not decay.

**Comment by tarantonio** [comment]
Did you checked ID 2317?

**Comment by peonso** [comment]
Fresh corpse is not decaying, just the ones that are not containers.

**Comment by peonso** [comment]
Gonna go with this, the important ones.

3130->3059
3131->3059
3132->3059
3060->3061
3133->3061
3134->3061
3117->2911
3118->2912
3115->2856

**Comment by tarantonio** [comment]
Ahh, I got it sorry!

**Comment by tarantonio** [comment]
First of all, chek the leaked files, the original clean map and compare with our map.
I think those corpses don't have to stay, it's garbage tracked.

**Comment by tarantonio** [comment]
The same with all the garbage that are not corpses like weapons, armors, etc... I'm sure that the original leaked map don't have them

We need to make a clean.

**Comment by peonso** [comment]
It had some level of garbage on ground, most of what we have should go, but it's not totally clean.

**Comment by tarantonio** [comment]
I think the best way is to compare with leaked original clean map

**Comment by peonso** [comment]
I was checking corpses of those places, as exemple, _{x = 32174, y = 32146, z = 11}_ and _{x = 33015, y = 32405, z = 12}_. Comparing ids with leaked map don't help as items have different proprieties, what are a monster corpse to real datapack might not be here, and don't worth the effort to make it all the same, better fixing those minor issues.

The clean should be visual =S

**Comment by peonso** [comment]
https://github.com/peonso/tibialegacyserver/commit/f9fd602ee7772da048b86d634497ef633093fa4f
