### ISSUE TITLE
Better monster path finding

### ISSUE THREAD

**Issue by peonso** [peonso/tibialegacyserver#54]
https://youtu.be/a9FbrBmOseI

**Comment by peonso** [comment]
https://github.com/babymannen/theforgottenserver-7.4/commit/9b01f8bb3abe95df0c3c8012a72c6ebe0fed3db3

**Comment by diegorodriguesvieira** [comment]
It works?

**Comment by peonso** [comment]
I'm waiting your pull request at OTHire repo. hahaha

**Comment by diegorodriguesvieira** [comment]
hahahaha with above code?

**Comment by diegorodriguesvieira** [comment]
http://paste.ubuntu.com/23156889/

**Comment by diegorodriguesvieira** [comment]
**In monster.cpp**
`if (tile && (tile->__queryAdd(0, this, 1, FLAG_PATHFINDING) == RET_NOERROR)) {`
