### ISSUE TITLE
Review monster spells

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#55]
There is a lot of differences in monster files regarded to spells compared to Tibia leaks.
I think the best way to do this is to make a script to transform leaked files to xml (including loots, that are also different)

**Comment by peonso** [comment]
Can you point it out? I think I did all default monster based on leaked files, bosses might have things missing. Would be great to convert it, I got now knowledge though.

**Comment by tarantonio** [comment]
Did you checked all loots? I  only checked some of them and there are differences between yours and leaked files.
I have different monster files, but have differences too.
Same on npcs, I fixed a lot of them but I still think that convert the leaked files has to be more easy than to fix all differences.
I'm still looking for a method to make the convert.

**Comment by tarantonio** [comment]
You can close this, I double checked the issue and didn't find any differences now. Probably my mistake, I'm sorry.
