### ISSUE TITLE
npc obi.lua

### ISSUE THREAD

**Issue by ghost** [peonso/tibialegacyserver#57]
you may want to change this line 
https://github.com/peonso/tibialegacyserver/blob/master/server/data/npc/scripts/Obi.lua#L60

from
`shopModule:addBuyableItem({'scroll'}, 2149, 5)`

to
`shopModule:addBuyableItem({'scroll'}, 1949, 5)`

lols on whoever wrote that line, i'm guessing that it has been abused in countless servers.

**Comment by peonso** [comment]
Probably, already removed a lot of abusable shit from the npcs. There are probably more, thanks for helping.
