### ISSUE TITLE
Rookgaard System Fix

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#62]
Here we need some Rookgaard system, when you are in mainland and got killed under level 6 and you have to return to Rookgaard.

[https://otland.net/threads/7-72-othire-0-0-1b-based-in-otserv-trunk-latest.212153/page-68#post-2338625](https://otland.net/threads/7-72-othire-0-0-1b-based-in-otserv-trunk-latest.212153/page-68#post-2338625)
We had the code working on our server, notice the post on OTLand and the next posts with fixes.

**Comment by peonso** [comment]
I will let this for the end, since I'm using clean OTHire sources until now, and it will give me too much trouble as OTHire is being updated constantly lately.

**Comment by peonso** [comment]
https://gist.github.com/peonso/38e0a7d34b6312f9e8a464b631a5940e

**Comment by peonso** [comment]
@tarantonio 

this one you linked me is bugged, it is sending lost level message before player actually loses level (when he nearby loses it). And is downgrading player to rook when it stills level 6, nearby 5, but still 6. I'm trying to fixing it.
