### ISSUE TITLE
The Oracle / The Gatekeeper Fix

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#63]
I think that on 7.72 RL version those npcs allowed you to go to mainland when you was >= 8, here is the leaked code of the oracle npc:

```
ADDRESS,"hello$",Level>=8,! -> "%N, ARE YOU PREPARED TO FACE YOUR DESTINY?"
ADDRESS,"hi$",Level>=8,!    -> *
ADDRESS,"greet",Level>=8,!  -> *
```

**Comment by peonso** [comment]
What is actually wrong?

**Comment by tarantonio** [comment]
Now is level = 8 instead of >=8

**Comment by peonso** [comment]
Code seems fine, you tested?

https://github.com/peonso/tibialegacyserver/blob/18828ef93ba0d7b1f81744281776d4537becfbf4/server/data/npc/scripts/The%20Gatekeeper.lua#L27

**Comment by tarantonio** [comment]
I just tested and it's working fine now!
