### ISSUE TITLE
Invisible bug

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#68]
I found a bug.

You become invisible as a GM.
Someone stays in the same tile as you.
You become visible.

The other user change their outfit to yours like this:
![2016-09-14 10_23_30-otclient](https://cloud.githubusercontent.com/assets/7066891/18505060/bdb14448-7a65-11e6-801a-169120c444a0.png)

In this shot on the left the GM become invisible again and the user is in the same tile as GM
In the right shot you can see the bug, Tarantonio is using a GM outfit and the same name as the GM

I'm using OTCLient.

With the normal Tibia client it's worse, if you do the same, you can't do nothing once you reproduce the bug:
![2016-09-14 10_30_51-tibia](https://cloud.githubusercontent.com/assets/7066891/18505224/991c1ca6-7a66-11e6-82bc-91065131bf51.png)
It changes the oufits and names, but in the user side you are like paralyzed and can't move.
The GM can move but it becomes crazy, you move all two characters.

With two tibia clients, it's crazy:
![2016-09-14 10_35_23-tibia](https://cloud.githubusercontent.com/assets/7066891/18505388/48515204-7a67-11e6-9081-ab581c90b709.png)

The only solution for user is to relogin.

**Comment by peonso** [comment]
https://github.com/TwistedScorpio/OTHire/issues/78
