### ISSUE TITLE
Website bugs

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#69]
- [x] When you are logged in and you want to go to map page, you got leaded to my account page.
- [ ] A minor bug with purchase buttons on shop page:
  ![2016-09-14 10_44_12-tibia legacy server - opentibia](https://cloud.githubusercontent.com/assets/7066891/18505657/8aa88590-7a68-11e6-8ba1-122cad5c2b53.png)

**Comment by tarantonio** [comment]
Didn't notice you have another post with website bugs, you can merge both two

**Comment by peonso** [comment]
Second one is a work in progress pointed in #40, fixing the first one now, thanks for the report.
