### ISSUE TITLE
Bright Sword Quest minor fix

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#72]
Why is a power ring here? --> {x = 32613, y = 32220, z = 10}

That power ring is suposed to be teleported from first lever, if you have one there there is no sense to teleport one

**Comment by peonso** [comment]
It is not teleported, I checked leaked files.

**Comment by peonso** [comment]
It is not teleported, I checked leaked files. The ring spawns there, what matters for it to work or not is the barrel.

**Comment by tarantonio** [comment]
I checked leaked files today too. You are right! Closing this now.
