### ISSUE TITLE
Proposal: Tibia Legacy Custom Client

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#74]
Why not a Legacy Custom Client based on OTClient or similar?

The goal is to remove all of unnecessary things (like change IP etc...) not needed and add the server IP in source.
Custom Background and music will be a good thing too!
Also interesting is to add some antibot features.

Something like this, but more elaborated:
![2016-09-22 16_56_16-otclient](https://cloud.githubusercontent.com/assets/7066891/18753493/cb66bf24-80e5-11e6-9df2-f90e15171b7e.png)

**Comment by peonso** [comment]
My plan was just to work on this server side, maybe in the future though, would be good to develop it in another repository.

**Comment by diegorodriguesvieira** [comment]
I've done it, I can help you...

**Comment by peonso** [comment]
I have a default client theme if you guys want, but would really like to work on it in another repository, to avoid mess and confusion.

![default-client-theme](http://i.imgur.com/sZuEqy6.png)

**Comment by tarantonio** [comment]
Can you show login screen? It's nice.
Open a Repository for Legacy Client!

**Comment by diegorodriguesvieira** [comment]
Lets go do it guys! 
https://github.com/diegorodriguesvieira/otclient772

**Comment by peonso** [comment]
http://imgur.com/a/oNHuH

**Comment by diegorodriguesvieira** [comment]
@tarantonio add me on skype: diego.ldn

**Comment by tarantonio** [comment]
@diegorodriguesvieira sorry I don't like to use skype.

**Comment by tarantonio** [comment]
@peonso I like to make something similar to your client, but I like the login screen more simple, and we can make a custom background and music.
