### ISSUE TITLE
Map fix - Desert isle corpse

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#75]
As seen on Real Tibia (leaked files):
![2016-09-23 08_40_46-0996-0988-09 sec_ - remere s map editor](https://cloud.githubusercontent.com/assets/7066891/18776506/edbe775e-8169-11e6-8489-8de3a013cdea.png)
![2016-09-23 08_40_36-0996-0988-09 sec_ - remere s map editor](https://cloud.githubusercontent.com/assets/7066891/18776508/f284c09a-8169-11e6-9d56-f1b3057307f9.png)

**Comment by peonso** [comment]
Gonna commit it soon.
