### ISSUE TITLE
Devil Helmet Quest

### ISSUE THREAD

**Issue by Jhol55** [peonso/tibialegacyserver#76]
First of all, sorry for my English, I'm learning.

In the room of the cyclops,in the position of the 1st chest is a hole with fire, where is the key, the door isn't locked, and the lever don't work.

(I already changed the 1st chest with the hole with fire)

![captura de tela de 2016-09-24 09 01 39](https://cloud.githubusercontent.com/assets/22240143/18808372/a9c752aa-8236-11e6-923b-930d2ebb017e.png)

**Comment by peonso** [comment]
Assume any quest not ticked in #47 is bugged, thanks for reporting anyway.
