### ISSUE TITLE
Npc Bug

### ISSUE THREAD

**Issue by Jhol55** [peonso/tibialegacyserver#78]
I'm trying to buy a spell, but look what happens.

![captura de tela de 2016-09-27 13 14 55](https://cloud.githubusercontent.com/assets/22240143/18882214/b7332308-84b4-11e6-9015-3cfcecc5e3fe.png)

**Comment by peonso** [comment]
Only with this npc?

**Comment by Jhol55** [comment]
I'm playing and testing, I will check all Venore npcs first

Edit:

I have found that vocations are already coming with magic, I can use exura, exiva...

**Comment by Jhol55** [comment]
I have found that vocations are already coming with magic, I can use exura, exiva...

**Comment by peonso** [comment]
You can edit that in [spells.xml](https://github.com/peonso/tibialegacyserver/blob/master/server/data/spells/spells.xml) replace `needlearn="0"` for `needlearn="1"` everywhere.

**Comment by Jhol55** [comment]
Hello @peonso

I found a bug in the Npc Chatterbone:

![captura de tela de 2016-09-29 12 37 41](https://cloud.githubusercontent.com/assets/22240143/18961635/0c05df98-8644-11e6-8418-118d7b5227fb.png)

And in the Npc Digger, when I try to sell empty vials:

![captura de tela de 2016-09-29 12 43 38](https://cloud.githubusercontent.com/assets/22240143/18961695/3ead2000-8644-11e6-8f68-e0cab6103576.png)

And the Npc Smiley does the same as Asrak bug...

**Comment by tarantonio** [comment]
Cipsoft has a unique script for magic npcs that is called inside the magic npc scripts.
You modify one script and it affects all npcs.
Same with bank script.
Can we make something similar here?

**Comment by peonso** [comment]
Probably
