### ISSUE TITLE
Insane skill gain after update skills from admin page

### ISSUE THREAD

**Issue by tarantonio** [peonso/tibialegacyserver#80]
![2016-11-04 13_48_49-otclient](https://cloud.githubusercontent.com/assets/7066891/20005997/b3fc7c76-a295-11e6-8ad8-94d2fa6e2412.png)
I don't know if it's engine related or something.
I updated the sword skill on a player to 120, then every one or two hits one skill is gained.
He obtained 175 sword in a matter of seconds killing rats

**Comment by peonso** [comment]
It happens with lower skills also?

**Comment by tarantonio** [comment]
No. At least in my tests. It happens after use the admin page to raise skills on a player

**Comment by peonso** [comment]
I couldn't reproduce it here, seems to be working as intended, you did it through AAC admin page or phpmyadmin?

**Comment by tarantonio** [comment]
Through AAC admin page

**Comment by peonso** [comment]
You are using this one? I really found no issue with it.

**Comment by tarantonio** [comment]
I will repeat the test tomorrow downloading again the sources.

**Comment by tarantonio** [comment]
I tried again, today I downloaded tls and OTHire (I see the exe is not updated):
![2016-11-07 15_07_10-tibia legacy server - opentibia](https://cloud.githubusercontent.com/assets/7066891/20060578/28b046f2-a4fc-11e6-93b5-b97b1c95a497.png)
5 rats 4 sword skill advances
![2016-11-07 15_04_59-otclient](https://cloud.githubusercontent.com/assets/7066891/20060537/edcd055c-a4fb-11e6-92f1-57f98c306a61.png)

BTW it's only happening on old players, if I create new one I can't reproduce the error

If you don't see any error on code here we can close the issue, maybe it's a db thing
