### ISSUE TITLE
error on compile help please

### ISSUE THREAD

**Issue by killineoo** [peonso/tibialegacyserver#83]
OS UBUNTU 12.4

root@localhost:/home/server/source# make
make  all-am
make[1]: Entering directory `/home/server/source'
g++ -DHAVE_CONFIG_H -I.    -I/usr/include/libxml2  -I/usr/include/lua5.1    -D__USE_MYSQL__     -D__ENABLE_SERVER_DIAGNOSTIC__ -std=c++11 -DSYSCONFDIR=\"/usr/local/etc\" -DPKGDATADIR=\"/usr/local/share/otserv\" -D_THREAD_SAFE -D__OLD_GUILD_SYSTEM__ -D_REENTRANT -Wall -g -O2 -MT databasemysql.o -MD -MP -MF .deps/databasemysql.Tpo -c -o databasemysql.o databasemysql.cpp
cc1plus: error: unrecognized command line option '-std=c++11'
make[1]: *** [databasemysql.o] Error 1
make[1]: Leaving directory `/home/server/source'
make: *** [all] Error 2

**Comment by peonso** [comment]
Not related with this datapack.

**Comment by diegorodriguesvieira** [comment]
@killineoo Try use ubuntu 14.04 or 16.04
