### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by LuckyMK** [peonso/tibialegacyserver#89]
Hey there.

I'm getting a error while compiling this OThire.  I've tried small edits but still not work

`monster.cpp: In member function ‘virtual void Monster::onCreatureMove(const Crea                                                                                                                                                             ture*, const Tile*, const Position&, const Tile*, const Position&, bool)’:
monster.cpp:279:43: error: invalid initialization of non-const reference of type                                                                                                                                                              ‘Position&’ from an rvalue of type ‘Position’
      Position& checkPosition = getPosition();`

**Comment by peonso** [comment]
Not related with this datapack.
