### ISSUE TITLE
Is possible to set up it for a 7.4 server?

### ISSUE THREAD

**Issue by fschuindt** [peonso/tibialegacyserver#90]
Hi there, folks.

I've compiled the OTHire and used this repository dataset to test some stuff, I can say it's a fantastic work. Congratulations.

So it's not a bug, just a question.

I'm trying to setup a 7.4 server, and followed those steps:

### OTHire
- Compiled latest OTHire sources and set up it locally with MariaDB.

### RME
- Downloaded last RME distro, configured to use the 7.4 `Tibia.dat`, `Tibia.pic` and `Tibia.spr`.
- Configured `clients.xml` to use otbm version 2 both for 7.6 and 7.4 maps.
- Set 7.4 version as default.
- Created a new map with OTServ version 0.6.0 and Client version 7.4.
- Using the 7.4 sprites, I've created a small testing island and loaded it into OTHire.

### Tibia Client
- Downloaded official Tibia 7.72 version.
- Used a IP Changer to connect to my local OTHire.
- Used the default 7.72 `.spr`, `.dat` and `.pic` files. I've tried to swap it to the 7.4 ones and the map was just a huge mess/bug, so I've turned back to the original 7.72 ones.

I'm able to login, walk around, everything fine.  
Even using the 7.72 sprites, my 7.4 map looks smooth.

But I've noticed it's using the 7.6 items sprites, Eg.: I've summoned a chain armor and it's using the new 7.6 sprite instead of the 7.4 one.

I suspect it's related to the `items/items.xml` and `items/items.otbm`. So I've downloaded the avesta74 and tried to use its `items.xml` and `items.otbm` files into OTHire. But again my map was turned into a huge bug/mess of sprites.

Am I doing it right?
Any tips?

**Comment by peonso** [comment]
Out of our scope here. Regarding this, my answer in PT-BR (try google translator if you are interested in this):

> Com relaçao a tua duvida pra converter o TLS pra 7.4, o caminho que eu tomaria seria ir alterando apenar os sprites do client, via ObjectBuilder, pra ir fazendo o mapa ficar o mais próximo parecido do 7.4 possivel, e ir fazendo as devidas alterações no mapa de forma manual mesmo (trabalheira danada). Você não tocaria nas sources, nem usaria nenhum tipo de arquivo realmente de protocolo 7.4, seu server seria um 7.72 com cara de 7.4, que é o que todos os servers 7.4 atuais são. Em questão de mecanicas, salvo engano o TLS tem um arquivo de spells.xml extra com os valores relativos a versão 7.4, faltaria UH trap, parcel block e alterar o script de rope pra nao permitir seu funcionamento com algo Em cima do rope spot.
