### ISSUE TITLE
[NETWORK]  ERROR: bind: Cannot assign requested address

### ISSUE THREAD

**Issue by killikilli** [peonso/tibialegacyserver#91]
hello, im can not connect at my server.., if im use my Global IP addres my external ip, server dont get online.. and im use my Local IP address im connect to my account and not connect to my character, and ask port 7171 is open... if im use my external ip on config.lua ask my port 7171 closed

:: StartUp - 11 May 2018 04:12:46
::
:: Running on host instance-1
:: Local IP address(es):  10.158.0.2  
:: Local ports:           7171  7172
:: Global IP address:     10.158.0.2

**Comment by peonso** [comment]
It's out of our scope, try OTLand support forum.
