### ISSUE TITLE
all screen black

### ISSUE THREAD

**Issue by Relyxia** [peonso/tibialegacyserver#92]
I just follow all guide othire 0.0.3 + this data pack + otclient
I have other engine + data pack and it's working perfectly with the same client
![image](https://user-images.githubusercontent.com/51744529/59701680-6c82bb00-91f6-11e9-84e1-c795f426114d.png)

But here it's not working
![image](https://user-images.githubusercontent.com/51744529/59701618-4c52fc00-91f6-11e9-9d26-3bd23e31d7ff.png)

**Comment by peonso** [comment]
This is just a datapack, the issues board is not supposed to handle support requests. Also the information given is lackluster, impossible to track any misstep taken.

**Comment by Relyxia** [comment]
> This is just a datapack, the issues board is not supposed to handle support requests. Also the information given is lackluster, impossible to track any misstep taken.

Well, I just follow your readme steps...

Please check it bro I just use OTHire 0.0.3 as you said, OTClient latest version and this datapack.

I didn't edit anything that could break this, I'm just using your recommended settings (btw one of your client links are broken)

Which other information do you need? I think I gave all the info, if not please can you tell me what's missing? Cuz I only changed the database details and I'm not going to share that
